name: "CI"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-multiarch:
    permissions:
      contents: read
      pull-requests: read
      packages: write
    env:
      REGISTRY: ghcr.io/siimpl
      IMAGE_NAME: cicd-tooling-emulated
      IMAGE_VERSION: 1.0
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:

      # Checkout buildah action github repository
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}