name: "CI"

on:
  push:
    branches:
      - main
  pull_request:

env:
  IMAGE_NAME: cicd-tooling
  IMAGE_VERSION: 1.0

jobs:
  build-multiarch:
    permissions:
      contents: read
      pull-requests: read
      packages: write
    runs-on: arc-runner-set-${{ matrix.architecture }}
    strategy:
      matrix:
        architecture: [amd64, arm64]
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/${{ matrix.architecture }}
          push: true
          tags: ${{ env.IMAGE_NAME }}
          cache-from: format('type=registry, ref={0}/{1}:builder-cache-{2}}', ghcr.io/siimpl, env.IMAGE_NAME, matrix.architecture)
          cache-to: format('type=registry, ref={0}/{1}:builder-cache-{2}}', ghcr.io/siimpl, env.IMAGE_NAME, matrix.architecture)
  publish-manifest:
    runs-on: arc-runner-set-arm64
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Publish Manifest
        run: |
          docker buildx imagetools create -t ghcr.io/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }} ghcr.io/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}-amd64 ghcr.io/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}-arm64